# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build for GOAMD64=v2
      run: go build -v ./...
      env:
        GOAMD64: v2

    - name: Build for GOAMD64=v3
      run: go build -v ./...
      env:
        GOAMD64: v3

    - name: Build purego
      run: go build -v -tags purego ./...

    - name: Build for GOARCH=arm64
      run: go build -v ./...
      env:
        GOARCH: arm64

    - name: Build for GOARCH=386
      run: go build -v ./...
      env:
        GOARCH: 386
